### ISSUE TITLE
Better README file

### ISSUE THREAD

**Issue by diegosueiro** [blu/zod#2]
I think it would be nice to have some kind of summary about what this method is trying to achieve and how.
Something based on the [article](https://www.cnx-software.com/2018/09/17/zero-overhead-destructors-in-c/) published in the CNXSOFT should be enough.

Also, it would be great to know how to check if the compiler used the constant-folding optimization.

**Comment by blu** [comment]
You are absolutely right, I will show disassemblies of the expected result and of failure as well. That will happen later today.
